### PR TITLE
[ES-1205037] Reproduce counter reset with merge iter unit test

### PR DESCRIPTION
**Pull request by yuchen-db**
please check out the branch and run the unit test. No plan to merge.

### CODE REVIEW

**Comment by hczhu-db** [comment]
Did the test case pass when you ran it on your laptop? @yuchen-db 
```
[hc.zhu@XYVT3X7065 ~/thanos(db_main)] go test github.com/thanos-io/thanos/pkg/dedup
ok      github.com/thanos-io/thanos/pkg/dedup   1.749s
```

**Comment by yuchen-db** [comment]
> Did the test case pass when you ran it on your laptop? @yuchen-db
> 
> ```
> [hc.zhu@XYVT3X7065 ~/thanos(db_main)] go test github.com/thanos-io/thanos/pkg/dedup
> ok      github.com/thanos-io/thanos/pkg/dedup   1.749s
> ```

It failed on my laptop
image

**Comment by yuchen-db** [comment]
> Did the test case pass when you ran it on your laptop? @yuchen-db
> 
> ```
> [hc.zhu@XYVT3X7065 ~/thanos(db_main)] go test github.com/thanos-io/thanos/pkg/dedup
> ok      github.com/thanos-io/thanos/pkg/dedup   1.749s
> ```

looks like you were on the db_main branch

**Comment by yuchen-db** [comment]
UPDATE: after removing resets in raw data the unit test PASSed. Prob need to use another piece of data or so.
image

**Pull request closed without merging**
